[config]
name = "macOS Menu Bar"

[config.js]
default = ['menu.js']

[chords]
'?-' = { name = "Menu Bar" }
'-0' = { name = "Menu Bar: Item 0 (Apple Logo)", args = [] }
'-([1-9])' = { name = "Menu Bar: Item $1", args = ["by-index", "$1"] }
'-([a-z]+[0-9]?)' = { name = "Menu Bar: By Letter $1", args = ["by-letters", "$1"] }
